services:
  tomcat:
    image: stroll_tomcat
    ports:
      - "8080:8080"
    networks:
      - stroll-net
    depends_on:
      - mysql

  mysql:
    image: stroll_mysql
    networks:
      - stroll-net

networks:
  stroll-net:
    name: stroll-net