services:
  tomcat:
    image: stroll_tomcat
    ports:
      - "8081:8080"
    networks:
      - stroll-net
    depends_on:
      - mysql

  mysql:
    image: stroll_mysql
    networks:
      - stroll-net
    volumes: # /home/aiden/mysql가 빈 폴더이어야 함, 없으면 Docker가 생성
      - /home/aiden/mysql:/var/lib/mysql

networks:
  stroll-net:
    name: stroll-net